//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KardeslerDikimEvi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Musteriler
    {
        public Musteriler()
        {
            this.Olcumler = new HashSet<Olcumler>();
        }
    
        public int ID { get; set; }
        public string AdiSoyadi { get; set; }
        public string Telefon { get; set; }
        public string Adres { get; set; }
        public System.DateTime Tarih { get; set; }
        public bool Aktifmi { get; set; }
    
        public virtual ICollection<Olcumler> Olcumler { get; set; }
    }
}
