//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KardeslerDikimEvi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Olcumler
    {
        public int ID { get; set; }
        public int MusteriID { get; set; }
        public decimal Fiyat { get; set; }
        public decimal Kapora1 { get; set; }
        public Nullable<decimal> Kapora2 { get; set; }
        public string Degerler { get; set; }
        public string Not { get; set; }
        public System.DateTime Tarih { get; set; }
    
        public virtual Musteriler Musteriler { get; set; }
    }
}
